Repository facebook/react-native, pull requests merged in 2019-07, with the labels that each got.

#25449 Upgrade JSC to 245459.0.0
  ReactAndroid/gradle.properties
Labels: Bug, CLA Signed, Contributor, Platform: Android

#25598 Fix Hermes binary path
  react.gradle
Labels: CLA Signed

#25700 Output correct source map path if Hermes not enabled
  react.gradle
Labels: Bug, CLA Signed, Platform: Android

#25710 [Android] Remove source map from release APK
  react.gradle
Labels: Bug, CLA Signed, Partner, Platform: Android, p: Facebook
