Repository facebook/react-native, pull requests merged in 2022-07, with the labels that each got.

#34098 [fix] backport FlipperConfiguration from main
  package.json
  packages/rn-tester/Podfile
  scripts/cocoapods/FlipperConfiguration.rb
  scripts/react_native_pods.rb
  template/ios/Podfile
Labels: CLA Signed, Platform: iOS, p: Facebook, Partner, Shared with React Native Team

#34159 Upgrade RN CLI to v8.0.3
  package.json
  yarn.lock
Labels: CLA Signed, Partner, p: Callstack, Shared with React Native Team

#34223 Fix/hermes in release
  .circleci/config.yml
  scripts/hermes/hermes-utils.js
Labels: CLA Signed, p: Facebook, Partner, Shared with React Native Team

#34228 [FIX] Build hermes from source on PR against stable
  .circleci/config.yml
  scripts/hermes/hermes-utils.js
  scripts/hermes/prepare-hermes-for-build.js
Labels: CLA Signed, p: Facebook, Partner, Shared with React Native Team

#34214 Fix React-bridging header not found for third party modules
  scripts/react_native_pods.rb
Labels: CLA Signed, Platform: iOS, p: Expo, Partner, Contributor, Bug, Shared with React Native Team

#34272 Upgrade RN CLI to v8.0.4
  package.json
  yarn.lock
Labels: CLA Signed, Partner, p: Callstack, Shared with React Native Team
