Repository facebook/react-native, pull requests merged in 2023-12, with the labels that each got.

#41456 Fix `build_codegen!` not finding `@react-native/codegen` in pnpm setups
  packages/react-native/scripts/cocoapods/__tests__/codegen-test.rb
  packages/react-native/scripts/cocoapods/codegen.rb
Labels: CLA Signed, p: Microsoft, Partner, Pick Request

#41781 Bump CLI to 12.2.0
  packages/community-cli-plugin/package.json
  packages/react-native/package.json
  yarn.lock
Labels: CLA Signed, Partner, p: Callstack, Pick Request

#41882 Bump CLI to 12.2.1
  packages/community-cli-plugin/package.json
  packages/react-native/package.json
  yarn.lock
Labels: CLA Signed, Partner, p: Callstack, Pick Request

#41479 BUMP CLI to v9.3.5
  package.json
  yarn.lock
Labels: CLA Signed

#41989 Prevent LogBox from crashing on long messages (#38005)
  .circleci/config.yml
  packages/react-native/Libraries/LogBox/Data/parseLogBoxLog.js
  packages/react-native/flow-typed/npm/ansi-regex_v5.x.x.js
  packages/react-native/package.json
  packages/rn-tester/Podfile.lock
Labels: CLA Signed, Partner, p: Shopify, Pick Request

#41277 [RN][CI]Update node installation on debian (0.71)
  .circleci/config.yml
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#39763 Fix overriding `EXCLUDED_ARCHS` when installing Hermes on RN v0.71
  scripts/cocoapods/__tests__/utils-test.rb
  scripts/cocoapods/utils.rb
Labels: CLA Signed

#41478 Bump CLI to v10.2.6
  package.json
  yarn.lock
Labels: CLA Signed

#41991 [Local] Bump hermes-engine
  packages/rn-tester/Podfile.lock
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#42040 [Local] Clean up invalid translations
  packages/react-native/ReactAndroid/src/main/res/devsupport/values-cb/strings.xml
  packages/react-native/ReactAndroid/src/main/res/devsupport/values-fb-rLS/strings.xml
  packages/react-native/ReactAndroid/src/main/res/devsupport/values-fb/strings.xml
  packages/react-native/ReactAndroid/src/main/res/views/uimanager/values-cb/strings.xml
  packages/react-native/ReactAndroid/src/main/res/views/uimanager/values-fb-rLS/strings.xml
  packages/react-native/ReactAndroid/src/main/res/views/uimanager/values-fb/strings.xml
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#42087 [RN][CI] Fix e2e test setup
  .circleci/configurations/commands.yml
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#41958 Fix monorepo package versions to version published with release
  package.json
  packages/community-cli-plugin/package.json
  packages/dev-middleware/package.json
  packages/eslint-config-react-native/package.json
  packages/metro-config/package.json
  packages/react-native/package.json
  packages/react-native/template/package.json
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#42082 Update these to use latest 0.73.x versions
  packages/babel-plugin-codegen/package.json
  packages/eslint-plugin-specs/package.json
  packages/react-native-babel-preset/package.json
  packages/react-native-babel-transformer/package.json
  packages/react-native-codegen-typescript-test/package.json
Labels: CLA Signed, p: Facebook, Partner, Pick Request
