Repository facebook/react-native, pull requests merged in 2023-03, with the labels that each got.

#36251 [0.71-stable] Update CLI to 10.2.0, Metro to 0.73.8
  package.json
  repo-config/package.json
  template/package.json
  yarn.lock
Labels: CLA Signed, p: Facebook, Partner

#36323 Cherry-picking changes in CI scripts for packages versions bumping
  .circleci/config.yml
  scripts/monorepo/__tests__/find-and-publish-all-bumped-packages-test.js
  scripts/monorepo/bump-all-updated-packages/index.js
  scripts/monorepo/constants.js
  scripts/monorepo/find-and-publish-all-bumped-packages.js
Labels: CLA Signed, p: Facebook, Partner

#36423 chore: Remove ruby-version from 0.71
  .gitignore
  .ruby-version
  Gemfile
  Gemfile.lock
  scripts/update-ruby.sh
  template/Gemfile
  template/_ruby-version
Labels: CLA Signed, Platform: iOS, p: Facebook, Partner

#36422 chore: remove Ruby Pinning from 0.70
  .gitignore
  .ruby-version
  Gemfile
  Gemfile.lock
  scripts/update-ruby.sh
  template/Gemfile
  template/_ruby-version
Labels: CLA Signed, Platform: iOS, p: Facebook, Partner

#36433 chore: Remove ruby-version from 0.69
  .gitignore
  .ruby-version
  Gemfile
  Gemfile.lock
  scripts/update-ruby.sh
  template/Gemfile
  template/_ruby-version
Labels: CLA Signed, Platform: iOS, p: Facebook, Partner

#36650 Fix platform Typings
  packages/react-native/Libraries/Utilities/NativePlatformConstantsAndroid.js
  packages/react-native/Libraries/Utilities/NativePlatformConstantsIOS.js
  packages/react-native/Libraries/Utilities/Platform.android.js
  packages/react-native/Libraries/Utilities/Platform.d.ts
  packages/react-native/Libraries/Utilities/Platform.ios.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#36654 Downgrade CLI to `alpha.0` to get Metro working again in CI
  packages/react-native/package.json
  yarn.lock
Labels: CLA Signed, p: Facebook, Partner, Bug, Pick Request

#36661 [0.72-stable] Fix localhost references in yarn.lock
  yarn.lock
Labels: CLA Signed, p: Facebook, Partner

#36657 Restore object with prerelease as string to unblock 0.72
  packages/react-native/Libraries/Core/ReactNativeVersionCheck.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#36573 RN [refactor]: bump and realign package versions by running a single …
  package.json
  scripts/monorepo/align-package-versions.js
  scripts/monorepo/bump-all-updated-packages/index.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#36746 fix(metro-config): fix and realign the situation for metro config for 0.72
  package.json
  packages/metro-config/index.js
  packages/metro-config/package.json
Labels: CLA Signed, p: Microsoft, Partner, Contributor, Pick Request
