Repository facebook/react-native, pull requests merged in 2023-08, with the labels that each got.

#38785 fix[AppContainer]: mount react devtools overlay only when devtools are attached
  packages/react-native/Libraries/ReactNative/AppContainer.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#38835 [LOCAL] Fabric Interop - Properly dispatch integer commands (#38527)
  packages/react-native/ReactAndroid/src/main/java/com/facebook/react/fabric/FabricUIManager.java
  packages/react-native/ReactAndroid/src/test/java/com/facebook/react/fabric/FabricUIManagerTest.kt
  packages/react-native/ReactAndroid/src/test/java/com/facebook/testutils/fakes/FakeBatchEventDispatchedListener.kt
  packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/component/MyLegacyViewManager.java
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#38784 fix: mount devtools overlay only if react devtools are connected
  Libraries/ReactNative/AppContainer.js
Labels: CLA Signed, p: Facebook, Partner

#38995 [0.71] Allow RCTBundleURLProvider to request an inline source map
  React/Base/RCTBundleURLProvider.h
  React/Base/RCTBundleURLProvider.mm
  packages/rn-tester/Podfile.lock
  packages/rn-tester/RNTesterUnitTests/RCTBundleURLProviderTests.m
Labels: CLA Signed, p: Microsoft, Partner

#38890 chore(releases): improve bump oss script to allow less human errors (71 edition)
  package.json
  scripts/monorepo/bump-all-updated-packages/bump-utils.js
  scripts/monorepo/bump-all-updated-packages/index.js
  scripts/publish-npm.js
  scripts/trigger-react-native-release.js
Labels: CLA Signed, p: Microsoft, Partner, Contributor

#38980 [LOCAL] Add script poll maven
  .circleci/config.yml
  scripts/circleci/poll-maven.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#39039 cipolleschi/add maven polling
  .circleci/config.yml
  scripts/circleci/poll-maven.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#38888 chore(releases): improve bump oss script to allow less human errors (72 edition)
  package.json
  scripts/monorepo/bump-all-updated-packages/bump-utils.js
  scripts/monorepo/bump-all-updated-packages/index.js
  scripts/publish-npm.js
  scripts/trigger-react-native-release.js
Labels: CLA Signed, p: Microsoft, Partner, Contributor, Pick Request

#38892 chore(releases): rename bump-oss script to align with newer versions
  package.json
  scripts/publish-npm.js
  scripts/trigger-react-native-release.js
Labels: CLA Signed, p: Microsoft, Partner, Contributor
