Repository facebook/react-native, pull requests merged in 2023-07, with the labels that each got.

#38179 [0.69] Use `Content-Location` header in bundle response as JS source URL (#37501)
  React/Base/RCTJavaScriptLoader.mm
  React/CxxBridge/RCTCxxBridge.mm
Labels: CLA Signed, p: Facebook, Partner

#38180 [0.69] Bump CLI to ^8.0.7, Metro to 0.70.4
  package.json
  yarn.lock
Labels: CLA Signed, p: Facebook, Partner

#38142 Do not create RuntimeExecutor on non-JSI executors (#38125)
  packages/react-native/ReactAndroid/src/main/jni/react/jni/CatalystInstanceImpl.cpp
  packages/react-native/ReactCommon/cxxreact/CMakeLists.txt
  packages/react-native/ReactCommon/cxxreact/Instance.cpp
  packages/react-native/ReactCommon/cxxreact/React-cxxreact.podspec
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#38572 fix: bumped CLI to address broken backward compatibility
  package.json
  yarn.lock
Labels: CLA Signed

#38553 Port CircleCI Artifact downloads to speed up release testing to 0.72
  scripts/circle-ci-artifacts-utils.js
  scripts/npm-utils.js
  scripts/release-utils.js
  scripts/test-e2e-local-clean.js
  scripts/test-e2e-local.js
  scripts/testing-utils.js
  scripts/update-template-package.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request
