Repository facebook/react-native, pull requests merged in 2023-06, with the labels that each got.

#37869 [LOCAL] Set kotlin.jvm.target.validation.mode=warning on user projects
  packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/JdkConfiguratorUtils.kt
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#37876 Add web compat unit tests and fixes
  Libraries/Components/TextInput/TextInput.js
  Libraries/Components/TextInput/__tests__/TextInput-test.js
  Libraries/Components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
  Libraries/Components/View/View.js
  Libraries/Components/View/__tests__/View-test.js
  Libraries/Image/Image.android.js
  Libraries/Text/Text.js
  Libraries/Text/__tests__/Text-test.js
Labels: CLA Signed

#37993 fix(ios): fix `pod install --project-directory=ios` failing
  scripts/cocoapods/__tests__/codegen_utils-test.rb
  scripts/cocoapods/codegen_utils.rb
Labels: CLA Signed, p: Microsoft, Partner

#37994 fix(ios): fix `pod install --project-directory=ios` failing
  packages/react-native/scripts/cocoapods/__tests__/codegen_utils-test.rb
  packages/react-native/scripts/cocoapods/codegen_utils.rb
Labels: CLA Signed, p: Microsoft, Partner, Pick Request
