Repository facebook/react-native, pull requests merged in 2023-01, with the labels that each got.

#35681 fix(CI): prevent the e2e test from running on 0.71
  .circleci/config.yml
Labels: CLA Signed, p: Microsoft, Partner, Contributor, Pick Request

#35847 fix(scripts): add logic for version scripts to account for local E2E test versioning
  scripts/set-rn-version.js
  scripts/test-e2e-local.js
  scripts/version-utils.js
Labels: CLA Signed, p: Microsoft, Partner, Contributor

#35946 Cherry-picking monorepo CI scripts to 0.71-stable
  .circleci/config.yml
  package.json
  scripts/monorepo/__tests__/bump-package-version-test.js
  scripts/monorepo/__tests__/find-and-publish-all-bumped-packages-test.js
  scripts/monorepo/__tests__/for-each-package-test.js
  scripts/monorepo/align-package-versions.js
  scripts/monorepo/bump-all-updated-packages/bump-package-version.js
  scripts/monorepo/bump-all-updated-packages/index.js
  scripts/monorepo/check-for-git-changes.js
  scripts/monorepo/constants.js
  scripts/monorepo/find-and-publish-all-bumped-packages.js
  scripts/monorepo/for-each-package.js
  scripts/run-ci-e2e-tests.js
  scripts/setup-verdaccio.js
  scripts/template/initialize.js
Labels: CLA Signed, Type: Enhancement, p: Facebook, Partner

#35963 fix(0.71-stable/tests): attempting to fix iOS template tests
  .circleci/config.yml
  .node-version
  scripts/setup-verdaccio.js
  template/_node-version
Labels: CLA Signed, p: Facebook, Partner
