Repository facebook/react-native, pull requests merged in 2023-04, with the labels that each got.

#36768 fix(xcode): backport Xcode 14.3 fix to 70
  scripts/cocoapods/__tests__/codegen_utils-test.rb
  scripts/cocoapods/codegen_utils.rb
Labels: CLA Signed, p: Microsoft, Partner, Contributor

#36769 fix(xcode): backport Xcode 14.3 fix to 71
  scripts/cocoapods/__tests__/codegen_utils-test.rb
  scripts/cocoapods/codegen_utils.rb
Labels: CLA Signed, p: Microsoft, Partner, Contributor

#36767 fix(xcode): backport Xcode 14.3 fix to 69
  packages/rn-tester/Podfile
  scripts/react_native_pods.rb
Labels: CLA Signed, p: Microsoft, Partner, Contributor

#36874 fix(textinput): backporting of fixes for next 0.71 patch release
  ReactAndroid/src/main/java/com/facebook/react/views/text/CustomLetterSpacingSpan.java
  ReactAndroid/src/main/java/com/facebook/react/views/text/CustomStyleSpan.java
  ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextUpdate.java
  ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
  ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java
  ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundManager.java
Labels: CLA Signed, p: Microsoft, Partner, Contributor

#36875 fix(textinput): backporting of fixes for next 0.70 patch release
  ReactAndroid/src/main/java/com/facebook/react/views/text/CustomLetterSpacingSpan.java
  ReactAndroid/src/main/java/com/facebook/react/views/text/CustomStyleSpan.java
  ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextUpdate.java
  ReactAndroid/src/main/java/com/facebook/react/views/text/TextLayoutManagerMapBuffer.java
  ReactAndroid/src/main/java/com/facebook/react/views/textinput/BUCK
  ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
  ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java
  ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundManager.java
  ReactCommon/react/renderer/components/text/ParagraphState.h
  ReactCommon/react/renderer/components/text/conversions.h
  ReactCommon/react/renderer/components/textinput/androidtextinput/react/renderer/components/androidtextinput/AndroidTextInputState.cpp
  ReactCommon/react/renderer/components/textinput/androidtextinput/react/renderer/components/androidtextinput/AndroidTextInputState.h
Labels: CLA Signed, p: Microsoft, Partner, Contributor

#36976 [0.72] Bump Metro to 0.76.2, cherry pick Metro config updates
  package.json
  packages/metro-config/index.js
  packages/metro-config/package.json
  packages/react-native/package.json
  packages/react-native/template/package.json
  yarn.lock
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#37000 fix(textinput): backporting of fixes for next 0.69 patch release (V3)
  ReactAndroid/src/main/java/com/facebook/react/views/text/CustomLetterSpacingSpan.java
  ReactAndroid/src/main/java/com/facebook/react/views/text/CustomStyleSpan.java
  ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
  ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java
  ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundManager.java
Labels: CLA Signed, p: Microsoft, Partner, Contributor

#37081 Fix test e2e script
  scripts/test-manual-e2e.sh
Labels: CLA Signed, Partner, p: Shopify

#37084 fix(textinput): backporting of fixes for next 0.68 patch release
  ReactAndroid/src/main/java/com/facebook/react/views/text/CustomLetterSpacingSpan.java
  ReactAndroid/src/main/java/com/facebook/react/views/text/CustomStyleSpan.java
  ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactEditText.java
  ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java
  ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewBackgroundManager.java
  scripts/test-manual-e2e.sh
Labels: CLA Signed, p: Microsoft, Partner, Contributor
