Repository facebook/react-native, pull requests merged in 2023-11, with the labels that each got.

#41267 cipolleschi/fix test script
  scripts/test-e2e-local.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#41221 [0.73] Collection of Android picks for RC4
  packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactPlugin.kt
  packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/AgpConfiguratorUtils.kt
  packages/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/utils/AgpConfiguratorUtilsTest.kt
  packages/react-native/ReactAndroid/src/main/java/com/facebook/react/devsupport/BridgeDevSupportManager.java
  packages/react-native/ReactAndroid/src/main/java/com/facebook/react/devsupport/DevSupportManagerBase.java
  packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/devloading/DevLoadingModule.java
  packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/JSTimerExecutor.java
  packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/ReactHostImpl.java
  packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/ReactInstance.java
  packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIManagerHelper.java
  packages/react-native/gradle/libs.versions.toml
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#41276 [RN][CI]Update node installation on debian (0.72)
  .circleci/config.yml
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#41275 [RN][CI]Update node installation on debian (0.73)
  .circleci/config.yml
  .circleci/configurations/jobs.yml
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#41316 Bump CLI to v11.3.10
  packages/react-native/package.json
  yarn.lock
Labels: CLA Signed, Partner, p: Callstack, Pick Request

#41376 Make the interop-layer work with components with custom name
  packages/react-native/ReactCommon/react/renderer/components/legacyviewmanagerinterop/LegacyViewManagerInteropComponentDescriptor.mm
  packages/react-native/ReactCommon/react/renderer/components/legacyviewmanagerinterop/RCTLegacyViewManagerInteropCoordinator.mm
Labels: CLA Signed, Partner, p: Shopify, Pick Request

#41378 Fix RNTestProject testing on Android
  scripts/circle-ci-artifacts-utils.js
  scripts/test-e2e-local.js
  scripts/testing-utils.js
Labels: CLA Signed, Partner, p: Shopify, Pick Request

#41377 Symbolicate unhandled promise rejections
  packages/react-native/Libraries/LogBox/Data/LogBoxData.js
  packages/react-native/Libraries/promiseRejectionTrackingOptions.js
Labels: CLA Signed, Partner, p: Shopify, Pick Request

#41380 [RN][iOS] Improve Podspec dependencies and prepare support for multiple Apple platforms
  packages/react-native/Libraries/AppDelegate/React-RCTAppDelegate.podspec
  packages/react-native/Libraries/Blob/React-RCTBlob.podspec
  packages/react-native/Libraries/Image/React-RCTImage.podspec
  packages/react-native/Libraries/LinkingIOS/React-RCTLinking.podspec
  packages/react-native/Libraries/NativeAnimation/React-RCTAnimation.podspec
  packages/react-native/Libraries/Network/React-RCTNetwork.podspec
  packages/react-native/Libraries/PushNotificationIOS/React-RCTPushNotification.podspec
  packages/react-native/Libraries/Settings/React-RCTSettings.podspec
  packages/react-native/Libraries/Vibration/React-RCTVibration.podspec
  packages/react-native/React-Core.podspec
  packages/react-native/React/CoreModules/React-CoreModules.podspec
  packages/react-native/React/React-RCTFabric.podspec
  packages/react-native/ReactCommon/React-Fabric.podspec
  packages/react-native/ReactCommon/React-FabricImage.podspec
  packages/react-native/ReactCommon/React-Mapbuffer.podspec
  packages/react-native/ReactCommon/React-rncore.podspec
  packages/react-native/ReactCommon/jserrorhandler/React-jserrorhandler.podspec
  packages/react-native/ReactCommon/react/nativemodule/core/platform/ios/React-NativeModulesApple.podspec
  packages/react-native/ReactCommon/react/nativemodule/samples/ReactCommon-Samples.podspec
  packages/react-native/ReactCommon/react/renderer/debug/React-rendererdebug.podspec
  packages/react-native/ReactCommon/react/renderer/imagemanager/platform/ios/React-ImageManager.podspec
  packages/react-native/ReactCommon/react/renderer/runtimescheduler/React-runtimescheduler.podspec
  packages/react-native/ReactCommon/react/runtime/React-RuntimeHermes.podspec
  packages/react-native/ReactCommon/react/utils/React-utils.podspec
  packages/react-native/scripts/cocoapods/__tests__/codegen_utils-test.rb
  packages/react-native/scripts/cocoapods/__tests__/new_architecture-test.rb
  packages/react-native/scripts/cocoapods/__tests__/utils-test.rb
  packages/react-native/scripts/cocoapods/codegen_utils.rb
  packages/react-native/scripts/cocoapods/new_architecture.rb
  packages/react-native/scripts/cocoapods/utils.rb
  packages/react-native/scripts/react_native_pods.rb
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#41530 Update CLI to v12.1.1
  packages/community-cli-plugin/package.json
  packages/react-native/cli.js
  packages/react-native/package.json
  yarn.lock
Labels: CLA Signed, Partner, p: Callstack, Pick Request

#41622 Revert "RNTester-ios / RCTAppDelegate > correctly check for USE_HERMES Flag"
  packages/react-native/Libraries/AppDelegate/RCTAppDelegate.mm
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#41641 [RN][iOS] Fix React-FabricImage dependencies
  packages/react-native/ReactCommon/react/renderer/imagemanager/platform/ios/React-ImageManager.podspec
  packages/react-native/scripts/cocoapods/__tests__/codegen_utils-test.rb
  packages/react-native/scripts/cocoapods/codegen_utils.rb
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#41639 [0.73] Fix projects being broken on dependencies starting with `a..`
  packages/react-native-gradle-plugin/build.gradle.kts
  packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/ReactRootProjectPlugin.kt
  packages/react-native/template/android/build.gradle
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#41444 Correctly declare runtime dependencies
  packages/react-native-codegen/package.json
Labels: CLA Signed, p: Microsoft, Partner, Pick Request

#41457 Fix `build_codegen!` not finding `@react-native/codegen` in pnpm setups
  packages/react-native/scripts/cocoapods/__tests__/codegen-test.rb
  packages/react-native/scripts/cocoapods/codegen.rb
Labels: CLA Signed, p: Microsoft, Partner, Pick Request
