Repository facebook/react-native, pull requests merged in 2024-06, with the labels that each got.

#44757 feat: upgrade CLI to `13.6.8`
  packages/community-cli-plugin/package.json
  packages/react-native/package.json
  yarn.lock
Labels: CLA Signed, Partner, p: Callstack, Pick Request

#44764 [0.74] Update `eslint-plugin-jest` to 27.x, `@typescript-eslint` deps to 7.x
  package.json
  packages/eslint-config-react-native/package.json
  yarn.lock
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#45020 [LOCAL][RN][CI] Use bigger machines for Android Helloworld
  .github/workflows/test-all.yml
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#45022 [LOCAL] Disable test_js_e2e on the 0.75 release branch
  .circleci/configurations/jobs.yml
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#45033 [LOCAL][RN][Release Testing] Update the testing script to run with the community template
  scripts/release-testing/test-e2e-local.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#45038 [LOCAL][CI][Release] Forward inputs to Create Release composite action
  .github/actions/create-release/action.yml
  .github/workflows/create-release.yml
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#45039 [LOCAL] Configure git user before attempting to publish a release
  .github/actions/create-release/action.yml
Labels: CLA Signed, p: Facebook, Partner

#45057 [LOCAL][RN][CI] Fix release scripts to use GITHUB_REF and GITHUB_REF_NAME variables
  scripts/__tests__/npm-utils-test.js
  scripts/npm-utils.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#44793 feat: update CLI to 13.6.9
  packages/community-cli-plugin/package.json
  packages/react-native/package.json
  yarn.lock
Labels: CLA Signed, Partner, p: Callstack, Pick Request

#45123 [RN][CI] Bump react-native CLI dependency to alpha.9
  packages/community-cli-plugin/package.json
  packages/react-native/package.json
  yarn.lock
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#45134 [LOCAL][CI] Require cocoapods to hermes-engine podspec
  .github/actions/cache_setup/action.yml
  .github/actions/prepare-hermes-workspace/action.yml
  .github/actions/restore-hermes-workspace/action.yml
  .github/actions/test_ios_helloworld/action.yml
  .github/workflows/nightly.yml
  .github/workflows/publish-release.yml
  .github/workflows/test-all.yml
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#45144 [LOCAL][Release-Testing] Update the testing script to use the new template
  scripts/e2e/init-template-e2e.js
  scripts/release-testing/test-e2e-local.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#45158 [LOCAL][CI] Fix Helloworld ios jobs
  .github/actions/test_ios_helloworld/action.yml
  .github/workflows/nightly.yml
  .github/workflows/publish-release.yml
  .github/workflows/test-all.yml
  scripts/e2e/init-template-e2e.js
  scripts/utils/monorepo.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request
