Repository facebook/react-native, pull requests merged in 2024-03, with the labels that each got.

#43246 [RN][iOS]Rename BUILD_FROM_SOURCE to RCT_BUILD_HERMES_FROM_SOURCE
  .circleci/configurations/executors.yml
  .circleci/configurations/jobs.yml
  packages/react-native/sdks/hermes-engine/hermes-utils.rb
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#43341 [RN][iOS] Fix flipper for Xcode 15.3
  packages/react-native/scripts/cocoapods/utils.rb
  packages/react-native/scripts/react_native_pods.rb
  packages/rn-tester/Podfile.lock
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#43414 Update `@react-native-community/cli` to 13.6.2
  packages/community-cli-plugin/package.json
  packages/react-native/package.json
  yarn.lock
Labels: CLA Signed, Partner, p: Callstack, Pick Request

#43638 fix(iOS): add missing forward blocks to RCTRootViewFactory
  packages/react-native/Libraries/AppDelegate/RCTAppDelegate.mm
  packages/react-native/Libraries/AppDelegate/RCTRootViewFactory.h
  packages/react-native/Libraries/AppDelegate/RCTRootViewFactory.mm
Labels: CLA Signed, p: Expo, Partner, Contributor, Pick Request

#43616 [0.74] Fixes build from source on Android
  packages/react-native/ReactAndroid/build.gradle.kts
  packages/react-native/ReactAndroid/hermes-engine/build.gradle.kts
Labels: CLA Signed, p: Facebook, Partner, Pick Request
