Repository facebook/react-native, pull requests merged in 2024-09, with the labels that each got.

#46367 [0.75] RGNP - Remove unnecessary dependency on `gradle-tooling-api-builders` - serviceOf failure
  packages/react-native-gradle-plugin/react-native-gradle-plugin/build.gradle.kts
  packages/react-native-gradle-plugin/settings-plugin/build.gradle.kts
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#46169 (cherry-pick) fix: Hermes build for visionOS simulator (Release) (#45911)
  packages/react-native/sdks/hermes-engine/utils/build-ios-framework.sh
Labels: CLA Signed, Partner, p: Callstack, Pick Request

#46127 [LOCAL][CI] Fetch Github tags in the publish-release job
  .github/workflows/publish-release.yml
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#46301 [RN][CI] Zip slices to preserve symlinks
  .github/workflows/nightly.yml
  .github/workflows/publish-release.yml
  .github/workflows/test-all.yml
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#46431 [0.76] Bump Metro to 0.81.0-alpha
  package.json
  packages/community-cli-plugin/package.json
  packages/metro-config/package.json
  packages/react-native/package.json
  yarn.lock
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#46514 [RN][iOS] Fix SVC for lineBreakModeIOS
  packages/react-native/Libraries/Components/TextInput/RCTTextInputViewConfig.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#46643 [0.76] Update Metro to 0.81.0-alpha.2
  package.json
  packages/community-cli-plugin/package.json
  packages/metro-config/package.json
  packages/react-native/package.json
  yarn.lock
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#46645 [0.76] Simplify key handling in start command
  packages/community-cli-plugin/package.json
  packages/community-cli-plugin/src/commands/start/attachKeyHandlers.js
  packages/community-cli-plugin/src/utils/KeyPressHandler.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#46067 [0.74] Add support for handling `com.facebook.react.bridge.Dynamic` as parameter for TurboModules
  packages/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/DynamicNative.kt
  packages/react-native/ReactAndroid/src/main/java/com/facebook/react/internal/turbomodule/core/TurboModuleInteropUtils.java
  packages/react-native/ReactAndroid/src/main/jni/react/jni/JDynamicNative.cpp
  packages/react-native/ReactAndroid/src/main/jni/react/jni/JDynamicNative.h
  packages/react-native/ReactAndroid/src/main/jni/react/jni/OnLoad.cpp
  packages/react-native/ReactCommon/react/nativemodule/core/platform/android/ReactCommon/JavaTurboModule.cpp
  packages/react-native/ReactCommon/react/nativemodule/samples/platform/android/SampleLegacyModule.java
  packages/rn-tester/js/examples/TurboModule/SampleLegacyModuleExample.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#45993 fix(react-native): fix codegen failing in a pnpm monorepo setup
  packages/react-native-codegen/package.json
  packages/react-native/package.json
Labels: CLA Signed, p: Microsoft, Partner, Pick Request
