Repository facebook/react-native, pull requests merged in 2024-04, with the labels that each got.

#43708 [rn][ios][0.74][RC6] decouple RCTBridge+Private from jsinspector-modern
  packages/react-native/React/Base/RCTBridge+Inspector.h
  packages/react-native/React/Base/RCTBridge+Private.h
  packages/react-native/React/Base/RCTBridge.mm
  packages/react-native/React/CoreModules/RCTDevSettings.mm
  packages/react-native/React/CxxBridge/RCTCxxBridge.mm
  packages/react-native/ReactCommon/react/runtime/platform/ios/ReactCommon/RCTInstance.mm
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#43681 Upgrade `@react-native-community/cli` to 13.6.4
  packages/community-cli-plugin/package.json
  packages/react-native/package.json
  yarn.lock
Labels: CLA Signed, Partner, p: Callstack, Pick Request

#43345 [RN][iOS][0.71] Fix flipper for Xcode 15.3
  packages/rn-tester/Podfile.lock
  scripts/cocoapods/utils.rb
  scripts/react_native_pods.rb
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#43900 [Yoga][0.74] Fix archive for MacOS Catalyst
  packages/react-native/ReactCommon/yoga/Yoga.podspec
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#44007 [RN][iOS] Cherry Pick #43757 and #43994
  packages/react-native/Libraries/AppDelegate/RCTAppDelegate.mm
  packages/react-native/Libraries/AppDelegate/RCTRootViewFactory.h
  packages/react-native/Libraries/AppDelegate/RCTRootViewFactory.mm
  packages/react-native/React/Base/RCTBridgeProxy.h
  packages/react-native/React/Base/RCTBridgeProxy.mm
  packages/react-native/ReactCommon/react/nativemodule/core/platform/ios/ReactCommon/RCTTurboModuleManager.mm
  packages/react-native/ReactCommon/react/runtime/iostests/RCTHostTests.mm
  packages/react-native/ReactCommon/react/runtime/platform/ios/ReactCommon/RCTHost+Internal.h
  packages/react-native/ReactCommon/react/runtime/platform/ios/ReactCommon/RCTHost.h
  packages/react-native/ReactCommon/react/runtime/platform/ios/ReactCommon/RCTHost.mm
  packages/react-native/ReactCommon/react/runtime/platform/ios/ReactCommon/RCTInstance.h
  packages/react-native/ReactCommon/react/runtime/platform/ios/ReactCommon/RCTInstance.mm
  packages/react-native/ReactCommon/react/test_utils/ios/Shims/ShimRCTInstance.h
  packages/react-native/ReactCommon/react/test_utils/ios/Shims/ShimRCTInstance.mm
  packages/rn-tester/Podfile.lock
  packages/rn-tester/RNTesterPods.xcodeproj/project.pbxproj
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#43896 [Yoga][0.73] Fix archive for MacOS Catalyst
  packages/react-native/ReactCommon/yoga/Yoga.podspec
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#44281 [iOS][Privacy Manifest] Set up privacy manifest for React Native 0.71
  packages/rn-tester/PrivacyInfo.xcprivacy
  packages/rn-tester/RNTesterPods.xcodeproj/project.pbxproj
  scripts/cocoapods/utils.rb
  scripts/react_native_pods.rb
  template/ios/HelloWorld.xcodeproj/project.pbxproj
  template/ios/HelloWorld/PrivacyInfo.xcprivacy
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#44317 add privacy manifest to hello world template
  packages/react-native/template/ios/HelloWorld.xcodeproj/project.pbxproj
  packages/react-native/template/ios/HelloWorld/PrivacyInfo.xcprivacy
Labels: CLA Signed, Pick Request
