Repository facebook/react-native, pull requests merged in 2024-01, with the labels that each got.

#41993 chore: cherry picks for 0.71.15
  ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java
  ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewManagersPropertyCache.java
  packages/rn-tester/Podfile.lock
Labels: CLA Signed

#42106 Fix react-native-codegen
  packages/babel-plugin-codegen/package.json
  packages/eslint-plugin-specs/package.json
Labels: CLA Signed, p: Facebook, Partner

#42138 Fix New Arch build failing with `-std=c++20`
  packages/react-native/ReactCommon/react/renderer/core/PropsParserContext.h
Labels: CLA Signed, p: Microsoft, Partner, Pick Request

#42141 chore: align package versions
  package.json
  repo-config/package.json
  yarn.lock
Labels: CLA Signed

#42175 [Local][RN][General] 0.72 - migrate boost away from JFrog
  packages/react-native/ReactAndroid/build.gradle
  packages/react-native/third-party-podspecs/boost.podspec
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#42177 [0.71][RN][General] Migrate boost download url away from JFrog
  ReactAndroid/build.gradle
  third-party-podspecs/boost.podspec
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#42178 [0.70][RN][General] Migrate boost download url away from JFrog
  ReactAndroid/build.gradle
  third-party-podspecs/boost.podspec
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#42228 [RN][iOS] Fix symbol not found _jump_fcontext with use_frameworks!
  packages/react-native/scripts/cocoapods/utils.rb
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#42142 [RN][iOS] Disable Bitcode for Hermes
  .circleci/config.yml
  packages/react-native/sdks/hermes-engine/utils/build-apple-framework.sh
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#42222 Apply stack Symbolication patch part 1 & 2 to 0.71-stable (#41377) (#42079) (original #40914)
  Libraries/LogBox/Data/LogBoxData.js
  Libraries/promiseRejectionTrackingOptions.js
Labels: CLA Signed

#42229 [RN][iOS] Fix symbol not found _jump_fcontext with use_frameworks!
  scripts/cocoapods/utils.rb
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#42279 Bump CLI to 12.3.2
  packages/community-cli-plugin/package.json
  packages/react-native/package.json
  yarn.lock
Labels: CLA Signed, Partner, p: Callstack, Pick Request

#42283 [RN][iOS] Disable bitcode for Hermes
  .circleci/config.yml
  sdks/hermes-engine/utils/build-apple-framework.sh
Labels: CLA Signed

#42227 [RN][iOS] Fix symbol not found _jump_fcontext with use_frameworks!
  packages/react-native/scripts/cocoapods/utils.rb
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#42382 [RN][iOS] Fix race condition between A11yManager and UIManager
  packages/react-native/React/Modules/RCTUIManager.m
  packages/rn-tester/Podfile.lock
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#42662 Cherry-picking 'Call super.onRequestPermissionsResult in ReactActivity (#42478)' onto 0.71
  ReactAndroid/src/main/java/com/facebook/react/ReactActivity.java
Labels: CLA Signed, p: Facebook, Partner

#42706 Cherry-picking 'Avoid using Cocoapods 1.15 until it fixes an issue affection RN. (#42702)' onto 0.71
  packages/rn-tester/Gemfile
  packages/rn-tester/Podfile.lock
  packages/rn-tester/RNTesterPods.xcodeproj/project.pbxproj
  template/Gemfile
Labels: CLA Signed
