Repository facebook/react-native, pull requests merged in 2024-02, with the labels that each got.

#42734 [RN][iOS] Fix warning when loading RCTUIManager and A11yManager
  packages/react-native/React/Modules/RCTUIManager.m
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#42877 [LOCAL][0.73] fix: cannot find module `react-native-*/Libraries/Core/InitializeCore`
  packages/community-cli-plugin/src/utils/loadMetroConfig.js
Labels: CLA Signed, p: Microsoft, Partner, Pick Request

#42872 [LOCAL][0.72] Update Metro to ^0.76.9, CLI to ^11.4.0
  package.json
  packages/metro-config/package.json
  packages/react-native/package.json
  packages/react-native/template/package.json
  yarn.lock
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#42075 [RN][iOS] Improve Swift support for 3rd party libs
  packages/react-native/ReactCommon/React-Fabric.podspec
  packages/react-native/ReactCommon/react/debug/React-debug.podspec
  packages/react-native/ReactCommon/react/renderer/graphics/React-graphics.podspec
  packages/react-native/ReactCommon/react/utils/React-utils.podspec
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#43002 Fix overriding EXCLUDED_ARCHS when installing Hermes on RN v0.72
  packages/react-native/scripts/cocoapods/__tests__/utils-test.rb
  packages/react-native/scripts/cocoapods/utils.rb
Labels: CLA Signed, Pick Request

#42943 fix: fix codegen not finding all third-party libraries
  packages/react-native/scripts/codegen/generate-artifacts-executor.js
Labels: CLA Signed, p: Microsoft, Partner, Pick Request

#42991 [0.73-stable] Cherry-pick improvements to monorepo publish script
  .circleci/configurations/jobs.yml
  scripts/monorepo/__tests__/find-and-publish-all-bumped-packages-test.js
  scripts/monorepo/find-and-publish-all-bumped-packages.js
  scripts/monorepo/for-each-package.js
  scripts/releases-ci/README.md
  scripts/releases-ci/__tests__/publish-updated-packages-test.js
  scripts/releases-ci/publish-updated-packages.js
  scripts/releases/utils/monorepo.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#43095 Update CLI to 12.3.6
  packages/community-cli-plugin/package.json
  packages/react-native/package.json
  yarn.lock
Labels: CLA Signed, Partner, p: Callstack, Pick Request

#43096 Upgrade CLI to 11.4.1
  packages/react-native/package.json
  yarn.lock
Labels: CLA Signed, Partner, p: Callstack, Pick Request

#43088 [RN][iOS] Fix compiler flags passed to libraries
  packages/react-native/scripts/cocoapods/__tests__/new_architecture-test.rb
  packages/react-native/scripts/cocoapods/new_architecture.rb
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#43128 [RN][Release] Fix release testing script
  scripts/e2e/init-template-e2e.js
  scripts/release-testing/test-e2e-local.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#43097 Update CLI to 10.2.7
  package.json
  yarn.lock
Labels: CLA Signed, Partner, p: Callstack

#43245 [RN][iOS]Rename BUILD_FROM_SOURCE to RCT_BUILD_HERMES_FROM_SOURCE
  .circleci/configurations/executors.yml
  .circleci/configurations/jobs.yml
  packages/react-native/sdks/hermes-engine/hermes-utils.rb
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#43247 [RN][iOS]Rename BUILD_FROM_SOURCE to RCT_BUILD_HERMES_FROM_SOURCE
  .circleci/config.yml
  packages/react-native/sdks/hermes-engine/hermes-engine.podspec
  packages/react-native/sdks/hermes-engine/hermes-utils.rb
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#43240 [RN][IOS] Fix flags for new arch
  packages/react-native/scripts/cocoapods/__tests__/new_architecture-test.rb
  packages/react-native/scripts/cocoapods/new_architecture.rb
Labels: CLA Signed, p: Facebook, Partner, Pick Request
