Repository facebook/react-native, pull requests merged in 2025-03, with the labels that each got.

#49877 Fix elevation with border-radius set (#48982)
  packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/drawable/CompositeBackgroundDrawable.kt
Labels: CLA Signed, Pick Request

#49892 [0.79] Update Metro to ^0.82.0
  package.json
  packages/community-cli-plugin/package.json
  packages/metro-config/package.json
  packages/metro-config/src/index.flow.js
  packages/react-native/package.json
  yarn.lock
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#49890 [0.77] Fix Android Image `defaultSource` runtime error (#49097)
  packages/react-native/Libraries/Image/Image.android.js
  packages/react-native/Libraries/Image/ImageViewNativeComponent.js
  packages/react-native/Libraries/__tests__/__snapshots__/public-api-test.js.snap
  packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageManager.kt
Labels: CLA Signed, Pick Request

#49930 [LOCAL][RN][iOS][OldArch] Add missing loadFromSource method in the DefaultRNFactoryDelegate
  packages/react-native/Libraries/AppDelegate/RCTDefaultReactNativeFactoryDelegate.mm
  packages/rn-tester/RNTester/AppDelegate.mm
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#49789 [RN][Releases] Fix Publish template
  .github/workflow-scripts/publishTemplate.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#50031 [0.79] refactor(react-native-codegen): Replace `jscodeshift` with `@babel/core`
  package.json
  packages/babel-plugin-codegen/__tests__/__snapshots__/index-test.js.snap
  packages/react-native-codegen/e2e/__tests__/components/__snapshots__/GenerateViewConfigJs-test.js.snap
  packages/react-native-codegen/package.json
  packages/react-native-codegen/src/generators/components/GenerateViewConfigJs.js
  packages/react-native-codegen/src/generators/components/__tests__/__snapshots__/GenerateViewConfigJs-test.js.snap
  yarn.lock
Labels: CLA Signed, p: Expo, Partner, Pick Request

#50096 [0.77] community-cli-plugin: resolve cli-server-api via peer dependency on cli
  packages/community-cli-plugin/package.json
  packages/community-cli-plugin/src/commands/start/middleware.js
  packages/react-native/react-native.config.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#50098 [0.78] community-cli-plugin: resolve cli-server-api via peer dependency on cli
  packages/community-cli-plugin/package.json
  packages/community-cli-plugin/src/commands/start/middleware.js
  packages/react-native/react-native.config.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#50127 [0.77] Metro minimum to 0.81.3, fix "_interopRequireDefault is not a function"
  package.json
  packages/community-cli-plugin/package.json
  packages/metro-config/package.json
  packages/metro-config/src/index.flow.js
  packages/react-native/package.json
  yarn.lock
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#50130 [RN][CI][Releases] Remove the v prefix from the version passed by GHA to the script
  .github/workflow-scripts/publishTemplate.js
Labels: CLA Signed, p: Facebook, Partner, Pick Request

#50238 [0.76][github] Fix upload-artifact version on maestro android
  .github/actions/maestro-android/action.yml
Labels: CLA Signed, p: Expo, Partner, Pick Request
